### ISSUE TITLE
Parsing failures

### ISSUE THREAD

**Issue by daveginberry** [SOLiNARY/torn-spy-parse#1]
Keep getting parse fails.  Could it be conflicting with Torn Tools.  Using inside Chrome on Chromebook. Other Torn tampermonkey scripts working fine.

**Comment by SOLiNARY** [comment]
@daveginberry I'm using it with TornTools on Chrome too.
Can you clarify on:
- which theme u use Dark/Light?
- is "Honor Names" setting in "General" settings tab ON/OFF?
- are you using Army job to generate spies or other company? if company, which one?

if you can copy whole spy result (job special) html block & attach it, that would be very helpful too!
You can get in console (F12) by running `document.getElementsByName("jobspecial")[0].innerHTML;` command **after** u get the spy result on screen.

**Comment by daveginberry** [comment]
Not using any theme - so I guess Light
Honor Names ON
Company You currently work as an Attorney at PeyDAmaN's Law $=INNOCENT which is owned by [-HellCat-](https://www.torn.com/profiles.php?XID=2534899).

Some errors in Console
TypeError: jobSpecialBlock is undefined
    GetSpyProfile moz-extension://35c13c2d-140e-40ca-a08f-95752545d349/userscripts/Torn SpyParse.user.js?id=0189d03b-b1e2-47a9-8ea6-eea25b2ca980:92
    GetSpyResult moz-extension://35c13c2d-140e-40ca-a08f-95752545d349/userscripts/Torn SpyParse.user.js?id=0189d03b-b1e2-47a9-8ea6-eea25b2ca980:78
[Torn SpyParse.user.js:84:17](moz-extension://35c13c2d-140e-40ca-a08f-95752545d349/userscripts/Torn%20SpyParse.user.js?id=0189d03b-b1e2-47a9-8ea6-eea25b2ca980)

Uncaught TypeError: document.getElementsByName(...)[0] is undefined
    <anonymous> debugger eval code:1
debugger eval code:1:10
document.getElementsByName("jobspecial")[0].innerHTML;
Uncaught TypeError: document.getElementsByName(...)[0] is undefined
    <anonymous> debugger eval code:1

I am not familiar with console stuff.  All the above was in firefox- running in Linux

**Comment by SOLiNARY** [comment]
@daveginberry updated script to work with Law Firms too.
